# Generated by Django 6.0.3 on 2026-03-18 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_alter_activityrecord_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, default='')),
                ('floors', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['name', 'id'],
                'managed': False,
            },
        ),
    ]
