# Generated by Django 6.0.3 on 2026-03-31 04:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('floor_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('observation_type', models.CharField(choices=[('photo', 'Photo'), ('note', 'Note')], db_index=True, max_length=16)),
                ('observation_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('photo_name', models.CharField(blank=True, max_length=255)),
                ('photo_preview_data_url', models.TextField(blank=True)),
                ('photo_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo_altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['-observation_time', '-created_at'],
            },
        ),
    ]
