# Generated by Django 6.0.3 on 2026-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_siteobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='photo_object_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='photo_object_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
