# Generated by Django 6.0.3 on 2026-04-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_activityrecord_facial_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='ethnic_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
