# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0009_activityrecord_ethnic_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteobservation",
            name="observation_type",
            field=models.CharField(
                choices=[("photo", "Photo"), ("note", "Note"), ("questions", "Short Qs")],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="siteobservation",
            name="seating_availability",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteobservation",
            name="greenery_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteobservation",
            name="noise_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteobservation",
            name="cleanliness",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
