# Generated by Codex on 2026-04-15

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0010_siteobservation_short_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonQuestionnaireResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("questionnaire_time", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "main_purpose",
                    models.CharField(
                        choices=[
                            ("errand_transit", "Errand / transit (necessary)"),
                            ("relaxing_passing_time", "Relaxing / passing time (optional)"),
                            ("meeting_people_social", "Meeting people / social activity"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "visit_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("1_4_times_per_week", "1-4 times per week"),
                            ("1_3_times_per_month", "1-3 times per month"),
                            ("first_time", "First time"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "stay_duration",
                    models.CharField(
                        choices=[
                            ("under_5_minutes", "<5 minutes"),
                            ("5_20_minutes", "5-20 minutes"),
                            ("20_60_minutes", "20-60 minutes"),
                            ("over_60_minutes", ">60 minutes"),
                        ],
                        max_length=64,
                    ),
                ),
                ("overall_rating", models.PositiveSmallIntegerField()),
                (
                    "social_interaction",
                    models.CharField(
                        choices=[
                            ("not_at_all", "Not at all"),
                            ("slightly", "Slightly"),
                            ("moderately", "Moderately"),
                            ("yes", "Yes"),
                            ("definitely", "Definitely"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "activity_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_responses",
                        to="collector.activityrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-questionnaire_time", "-created_at"],
            },
        ),
    ]
