# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0011_personquestionnaireresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityIdSequence",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("next_cluster_number", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "activity ID sequence",
                "verbose_name_plural": "activity ID sequences",
            },
        ),
    ]
