from __future__ import annotations

from base64 import b64encode
from pathlib import Path

JPEG_SOI_MARKER = b"\xff\xd8"
JPEG_SOS_MARKER = 0xDA
JPEG_SOI_CODE = 0xD8
JPEG_EOI_CODE = 0xD9
JPEG_STANDALONE_MARKERS = {0x01, *range(0xD0, 0xD8)}
JPEG_SOF_MARKERS = {
  0xC0,
  0xC1,
  0xC2,
  0xC3,
  0xC5,
  0xC6,
  0xC7,
  0xC9,
  0xCA,
  0xCB,
  0xCD,
  0xCE,
  0xCF,
}
SVG_GENERATOR_MARKER = "generated by indoor-publicspace-collector: jpg-floorplan-to-svg"
DEFAULT_MAX_SVG_SIDE = 2000


def convert_jpg_floorplan_to_svg(
  jpg_path: Path,
  svg_path: Path | None = None,
  *,
  overwrite: bool = False,
  max_svg_side: int = DEFAULT_MAX_SVG_SIDE,
) -> Path:
  """
  Convert a JPG floor plan to an SVG wrapper that embeds the JPG image data.

  The generated SVG can be displayed safely inside an <img> element and keeps
  percentage-based map coordinates consistent.
  """
  source = Path(jpg_path)
  if source.suffix.lower() not in {".jpg", ".jpeg"}:
    raise ValueError(f"Expected a .jpg/.jpeg file, got: {source.name}")
  if not source.exists() or not source.is_file():
    raise FileNotFoundError(f"JPG floor plan not found: {source}")

  target = Path(svg_path) if svg_path else source.with_suffix(".svg")
  if target.exists() and not overwrite:
    return target

  source_width, source_height = read_jpeg_dimensions(source)
  width, height = scaled_dimensions(source_width, source_height, max_svg_side)
  jpg_data_uri = to_jpeg_data_uri(source)

  svg_content = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    f"<!-- {SVG_GENERATOR_MARKER} -->\n"
    '<svg xmlns="http://www.w3.org/2000/svg" '
    f'width="{width}" height="{height}" viewBox="0 0 {width} {height}">\n'
    f'  <image href="{jpg_data_uri}" x="0" y="0" width="{width}" '
    f'height="{height}" preserveAspectRatio="xMidYMid meet" />\n'
    "</svg>\n"
  )

  target.write_text(svg_content, encoding="utf-8")
  return target


def should_regenerate_jpg_wrapper(svg_path: Path, jpg_path: Path) -> bool:
  """
  Regenerate lightweight legacy wrappers so embedded-map rendering stays stable.
  """
  if not svg_path.exists():
    return True

  try:
    with svg_path.open("r", encoding="utf-8", errors="ignore") as svg_file:
      header = svg_file.read(16_384).lower()
  except OSError:
    return True

  if SVG_GENERATOR_MARKER in header:
    return False
  if "data:image/jpeg;base64," in header:
    return False

  quoted_jpg_name = jpg_path.name.lower()
  if "<image" in header and quoted_jpg_name in header:
    return True

  return False


def scaled_dimensions(width: int, height: int, max_side: int) -> tuple[int, int]:
  if width <= 0 or height <= 0:
    raise ValueError("Image dimensions must be positive.")
  if max_side <= 0:
    return width, height

  largest_side = max(width, height)
  if largest_side <= max_side:
    return width, height

  scale = max_side / float(largest_side)
  scaled_width = max(1, int(round(width * scale)))
  scaled_height = max(1, int(round(height * scale)))
  return scaled_width, scaled_height


def to_jpeg_data_uri(jpg_path: Path) -> str:
  encoded_image = b64encode(jpg_path.read_bytes()).decode("ascii")
  return f"data:image/jpeg;base64,{encoded_image}"


def read_jpeg_dimensions(jpg_path: Path) -> tuple[int, int]:
  """
  Read JPEG dimensions from SOF markers without external dependencies.
  """
  with Path(jpg_path).open("rb") as image:
    if image.read(2) != JPEG_SOI_MARKER:
      raise ValueError(f"File is not a valid JPEG image: {jpg_path}")

    while True:
      marker_prefix = image.read(1)
      if not marker_prefix:
        break
      if marker_prefix != b"\xff":
        continue

      marker_type = image.read(1)
      while marker_type == b"\xff":
        marker_type = image.read(1)

      if not marker_type:
        break

      marker_code = marker_type[0]
      if marker_code in {JPEG_SOI_CODE, JPEG_EOI_CODE}:
        continue
      if marker_code in JPEG_STANDALONE_MARKERS:
        continue
      if marker_code == JPEG_SOS_MARKER:
        break

      segment_length_bytes = image.read(2)
      if len(segment_length_bytes) != 2:
        break

      segment_length = int.from_bytes(segment_length_bytes, "big")
      if segment_length < 2:
        raise ValueError(f"Invalid JPEG segment length in: {jpg_path}")

      if marker_code in JPEG_SOF_MARKERS:
        sof_payload = image.read(5)
        if len(sof_payload) != 5:
          break

        height = int.from_bytes(sof_payload[1:3], "big")
        width = int.from_bytes(sof_payload[3:5], "big")
        if width <= 0 or height <= 0:
          raise ValueError(f"Invalid JPEG dimensions in: {jpg_path}")
        return width, height

      image.seek(segment_length - 2, 1)

  raise ValueError(f"Could not determine JPEG dimensions for: {jpg_path}")
